// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/fiaas/fiaas-go-client/pkg/client/clientset/versioned/typed/fiaas.schibsted.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFiaasV1 struct {
	*testing.Fake
}

func (c *FakeFiaasV1) Applications(namespace string) v1.ApplicationInterface {
	return &FakeApplications{c, namespace}
}

func (c *FakeFiaasV1) ApplicationStatuses(namespace string) v1.ApplicationStatusInterface {
	return &FakeApplicationStatuses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFiaasV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
