// Code generated by lister-gen. DO NOT EDIT.

package v1

// ApplicationListerExpansion allows custom methods to be added to
// ApplicationLister.
type ApplicationListerExpansion interface{}

// ApplicationNamespaceListerExpansion allows custom methods to be added to
// ApplicationNamespaceLister.
type ApplicationNamespaceListerExpansion interface{}

// ApplicationStatusListerExpansion allows custom methods to be added to
// ApplicationStatusLister.
type ApplicationStatusListerExpansion interface{}

// ApplicationStatusNamespaceListerExpansion allows custom methods to be added to
// ApplicationStatusNamespaceLister.
type ApplicationStatusNamespaceListerExpansion interface{}
