#!/usr/bin/env bash
set -euo pipefail

KUBERNETES_VERSION="$1"
CLUSTER_NAME=fiaas-go-client-e2e
KIND_KUBECONFIG="$(mktemp)"

__cleanup() {
    kind delete cluster --kubeconfig "$KIND_KUBECONFIG" --name "$CLUSTER_NAME"
    rm "$KIND_KUBECONFIG"
}

trap __cleanup EXIT

kind create cluster --kubeconfig="$KIND_KUBECONFIG" --name "$CLUSTER_NAME" --image "kindest/node:$KUBERNETES_VERSION" --wait 30s

kubectl --kubeconfig="$KIND_KUBECONFIG" apply -f hack/fiaas-crds-v1.yml

export KIND_KUBECONFIG
go test --tags=e2e ./...
