---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.fiaas.schibsted.io
spec:
  conversion:
    strategy: None
  group: fiaas.schibsted.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    - fa
    singular: application
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: application-statuses.fiaas.schibsted.io
spec:
  conversion:
    strategy: None
  group: fiaas.schibsted.io
  names:
    kind: ApplicationStatus
    listKind: ApplicationStatusList
    plural: application-statuses
    shortNames:
    - status
    - appstatus
    - fs
    singular: applicationstatus
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
