// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/fiaas/fiaas-go-client/pkg/apis/fiaas.schibsted.io/v1"
	"github.com/fiaas/fiaas-go-client/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type FiaasV1Interface interface {
	RESTClient() rest.Interface
	ApplicationsGetter
	ApplicationStatusesGetter
}

// FiaasV1Client is used to interact with features provided by the fiaas.schibsted.io group.
type FiaasV1Client struct {
	restClient rest.Interface
}

func (c *FiaasV1Client) Applications(namespace string) ApplicationInterface {
	return newApplications(c, namespace)
}

func (c *FiaasV1Client) ApplicationStatuses(namespace string) ApplicationStatusInterface {
	return newApplicationStatuses(c, namespace)
}

// NewForConfig creates a new FiaasV1Client for the given config.
func NewForConfig(c *rest.Config) (*FiaasV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &FiaasV1Client{client}, nil
}

// NewForConfigOrDie creates a new FiaasV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *FiaasV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new FiaasV1Client for the given RESTClient.
func New(c rest.Interface) *FiaasV1Client {
	return &FiaasV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FiaasV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
