// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	fiaasschibstediov1 "github.com/fiaas/fiaas-go-client/pkg/apis/fiaas.schibsted.io/v1"
	versioned "github.com/fiaas/fiaas-go-client/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fiaas/fiaas-go-client/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/fiaas/fiaas-go-client/pkg/client/listers/fiaas.schibsted.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApplicationStatusInformer provides access to a shared informer and lister for
// ApplicationStatuses.
type ApplicationStatusInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ApplicationStatusLister
}

type applicationStatusInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApplicationStatusInformer constructs a new informer for ApplicationStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApplicationStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApplicationStatusInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApplicationStatusInformer constructs a new informer for ApplicationStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApplicationStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FiaasV1().ApplicationStatuses(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FiaasV1().ApplicationStatuses(namespace).Watch(options)
			},
		},
		&fiaasschibstediov1.ApplicationStatus{},
		resyncPeriod,
		indexers,
	)
}

func (f *applicationStatusInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApplicationStatusInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *applicationStatusInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fiaasschibstediov1.ApplicationStatus{}, f.defaultInformer)
}

func (f *applicationStatusInformer) Lister() v1.ApplicationStatusLister {
	return v1.NewApplicationStatusLister(f.Informer().GetIndexer())
}
